permalink: /:categories/:year/:month/:day/:title

exclude:
  - ".gitignore"
  - ".DS_Store"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "README.md"
  - "bower.json"
  - "package.json"
  - "bower_components"
  - "node_modules"

pygments: true
markdown: kramdown

toc:
  - head: '/index.html'
    body: []

  # - head: '/dashboard/index.html'
  #   body: []

  - head: '/deployment/web/index.html'
    body:
     - '/deployment/web/variants.html'
     - '/deployment/web/goals.html'
     - '/deployment/web/preview.html'
     - '/deployment/web/javascript.html'
     - '/deployment/web/google-analytics.html'
     - '/deployment/web/customisation.html'

  - head: '/api/index.html'
    body:
     - /api/authentication.html
     - /api/errors.html
     - /api/settings.html
     - /api/experiment-create.html
     - /api/experiment-read.html
     - /api/experiment-search.html
     - /api/experiment-record.html
     - /api/experiment-reset.html
     - /api/experiment-update.html
     - /api/experiment-delete.html

  - head: '/js/index.html'
    body: 
     - /js/quick-start.html
     - /js/client.html
     - /js/experiment.html
     - /js/base-experiment.html
     - /js/log.html
     - /js/contributing.html


