permalink: /:categories/:year/:month/:day/:title

exclude: [
  ".gitignore",
  ".DS_Store",
  "Gemfile",
  "Gemfile.lock",
  "Gruntfile.coffee",
  "README.md",
  "bower.json",
  "package.json",
  "bower_components",
  "node_modules"
]

pygments: true
markdown: kramdown
